[config]
default_to_workspace = false

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked"]

[tasks.rust-optimizer]
script = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer-arm64:0.12.7
"""

[tasks.test]
command = "cargo"
args = ["test", "--locked"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--tests", "--", "-D", "warnings"]

[tasks.all-github-actions]
dependencies = [
    "check",
    "build",
    "test",
    "fmt",
    "clippy",
    "rust-optimizer",
]

[tasks.generate-all-schemas]
script = """
    rm -rf schema
    rm -rf schemas
    mkdir schemas

    array=( account-nft mock-red-bank )
    for i in "${array[@]}"
    do
      :
      echo "$i"
      cargo run --package "$i" --example schema
      mkdir schemas/"$i"
      mv schema/"$i".json schemas/"$i"/"$i".json
    done

    rm -rf schema
"""
